### ISSUE TITLE
Officially define the criteria for regular

### ISSUE THREAD

**Issue by 333fred** [discord-csharp/meta#10]
Currently, we don't have an official participation level for what qualifies as regular. We do have a standard waiting period (20 days), but for participation level, I've seen various levels quoted, from 80th percentile to 90th percentile. I've nominated users in the past who made the lower participation level, but their campaigns received downvotes from other members as not meeting the participation criteria. I would like to propose that we make an official ruling on what qualifies here. The criteria I'd like to see officially stated (and then documented in `$roles`):

* Participation level. As the guild gets bigger and bigger, qualifying for percentile numbers will change over time, so I'd instead suggest a raw message count. This could also be easily abused, of course, but I'll count on the moderators to try and keep spammy users from hitting this.
* Participation streaks. There have been a few times where I have been on the edge about nominating a user, because when they're here they talk a bunch, but disappear for 4-5 days at a time. I would like to encourage weekend posters to continue to be a part of the community, and an official stance on this would be helpful so I can determine who meets the criteria for nomination.
* Infractions. This is currently kinda going without saying, that users who have infractions aren't nominated for a while. I don't think that this should necessarily be as iron-clad a stance as the above points (given that infraction severity can vary wildly), but I do think that it should be called out in `$roles`. I would suggest something like this wording: `Regulars are here often and know their way around the server. They've been on the server for at least 20 days, regularly chat in the guild, and have proven that they follow guild #rules. ...`

**Comment by Scott-Caldwell** [comment]
> Participation level. As the guild gets bigger and bigger, qualifying for percentile numbers will change over time, so I'd instead suggest a raw message count.

I've been using 5-6 messages/day as my rule of thumb lately, which I think comes out to around the 90th percentile currently.

> Participation streaks. There have been a few times where I have been on the edge about nominating a user, because when they're here they talk a bunch, but disappear for 4-5 days at a time. I would like to encourage weekend posters to continue to be a part of the community, and an official stance on this would be helpful so I can determine who meets the criteria for nomination.

This one is likely a bit difficult to define. When I'm looking for consistency here, I'm usually just looking to make sure the nominee:
- Doesn't pop in once every few months to post a bunch for a short while and then disappear again.
- Hasn't posted most of their recent messages within the past week. (This can be a bit misleading, though, because it's also possible for them to have still maintained the 5-6 message/day average throughout the rest of the month and just gone above and beyond in the past week.)

> Infractions. This is currently kinda going without saying, that users who have infractions aren't nominated for a while. I don't think that this should necessarily be as iron-clad a stance as the above points (given that infraction severity can vary wildly), but I do think that it should be called out in `$roles`. I would suggest something like this wording: `Regulars are here often and know their way around the server. They've been on the server for at least 20 days, regularly chat in the guild, and have proven that they follow guild #rules. ...`

Seems reasonable to me.

**Comment by Inzanit** [comment]
Happy to raise this with staff - I think it would be good to create a tag for the definition.

**Comment by NullEntity** [comment]
I believe it's important that users are active in specifically the on topic channels too.

**Comment by 333fred** [comment]
> I believe it's important that users are active in specifically the on topic channels too.

Depends. We've had a few blues who are pretty-much only offtopic, and I'm fine that. Regular says nothing about skill level or amount that a user actually helps or asks questions in the on-topic channels, that's what Associate is for.

**Comment by RubyNova** [comment]
Actually, we don't include offtopic channels when deciding who gets regular.

This is actually one of the more well-defined requirements for regular. 😅

**Comment by 333fred** [comment]
I'm going to bump this again: we have enough people on the server now that 8.567 messages/day is enough for the 93rd percentile. I don't know if this meets the criteria. @Inzanit @RubyNova, can y'all have a discussion on this and define something in terms of messages/day?

**Comment by patrickklaeren** [comment]
I personally don't deem there to be "regular requirements", there's a 20-day requirement, sure, but I believe it's way more about consistency if anything. With the survey that we just posted we're now talking about finally making regular automatic, based on XP/levelling so this discussion doesn't need to keep happening. The voting system doesn't scale with the size of the server and that needs to change with the way we maintain regulars.

**Comment by patrickklaeren** [comment]
Somewhat solved now with the XP-levelling system introduced. I'll close this out since there haven't been many more complaints.
