### ISSUE TITLE
Temp VCs

### ISSUE THREAD

**Issue by Adomix** [discord-csharp/meta#11]
Voice chat often gets cluttered by several people helping each other and also the (totally allowed) offtopic convos. There are many bots out there that make voice chats based on a command typed. For example, in the sea of thieves server. In that server, you type what size/type of group and it creates a voice channel for you and your partners with the specified amount of people.

**Comment by 333fred** [comment]
I'm tentatively in favor of this idea, as long as these bots can clean up after everyone has left the VC.

**Comment by tannergooding** [comment]
This is similar to, but more broad than https://github.com/discord-csharp/meta/issues/5

**Comment by 333fred** [comment]
One reason I like this, as opposed to the solution from #5, is that this addresses Inz's concern about having too many channels. These are ephemeral channels that will go away (at least, they are in my theory of how these bots work).

**Comment by KeithRitter** [comment]
@333fred Yep. From the SoT server channels get added to the bottom, so out of the way, then deleted ones everyone leaves.

**Comment by Adomix** [comment]
@333fred Yes, and yes it cleans up after they all leave

**Comment by Adomix** [comment]
![Don't-look-at-this](https://mangoman.me/ss/GrayCanderousOrdoIsACombee.png)
![Don't-look-at-this](https://mangoman.me/ss/ParchedSalaciousB.CrumbIsASeadra.png)

**Comment by Jay-Madden** [comment]
I will say ive noticed a much higher vc presence over the past few months. It makes sense to facilitate that as much as possible.

**Comment by Inzanit** [comment]
VC presence seems to fluctuate a lot - last couple of weeks has been pretty tame, not a lot happening. I haven't seen people have an issue finding voice channels and whatnot.

I'll close it out but definitely happy to revisit if we find this is an issue.
