### ISSUE TITLE
Dedicated Lessons Support.

### ISSUE THREAD

**Issue by RubyNova** [discord-csharp/meta#12]
With all the recent talk of a github pages-based resource centre type of thing, a thought cropped into my mind last night that might have a place in said github pages - dedicated lessons and/or sessions of some kind.

 ### So, how would this work, roughly?

The idea would probably not be a "main feature" of the guild or anything, as I imagine many people may not want to do this, but for those of us who *would* be interested, I imagined that the process would look something like:

(Yes I am starting at 0, arrays do not start at 1, stop it)
0 - Have a dedicated role that would permit the use of the "Priority Speaker" permission (or voice mute permission, but the former would be greatly preferred, assuming people would behave).
1 - The community member giving the talk, class, whatever you wanna call it (I'll be referring to this collectively as "talk" for the rest of this discussion), this specific role. Perhaps like a Mentor or Teacher role, which has been explicitly discussed in the past, but this is the first time I can see an actual use for it.
2 - The talk will be organised in advanced to be on a specific day, at a specific time. This schedule will be public and updated regularly.
3 - The talk can be related to any software dev and/or computer science subject, assuming there is at least some examples in C#, .NET, or a clear relation to the ecosystem in some other fashion. This means talks surrounding language interop would be permitted, as long as one of the languages is a .NET language (for example).
4 - Optionally, should the community member providing the talk wish to, a C# Discord youtube channel will be set up to upload these talks to and put in relevant playlists if it is part of a series they are doing for other community members. This would require the person providing the talk to record the talk and then send it to someone who has access e.g. staff.

### So why would anyone want to do this?

The core idea behind this is basically to give members a platform to share what they know in a more dedicated format, if they want to. It would also allow members of the community who enjoy providing dedicated educational content a much easier medium to do so. It also means that common topics and questions would get an FAQ-style support in a format that many people ask for (and we subsequently claim is no good, myself included on that front) in the form of videos. Since we are primarily a Q&A-based discord, this would also allow people to ask *specific* questions surrounding what is being explained in whatever past or live talk they are watching/participating in.

Other benefits include more miscellaneous things, such as exposure to topics people may not be aware even exist or are just niche. If it works as intended, it would prove a nice strong sense of variety to the community that, at times, I feel we don't entirely have. There is so much in the wonderful ecosystem that is .NET, it would be great to provide the opportunity to explore it as much as possible.

### What would be the downsides?

Primarily, it would most likely have a few restrictions and may mean additional moderation overhead, a little bit like the Journalist role we have now but stricter. There is also no guarantee that enough of the community would be interested, but last I checked we were at 8,600 members. I'm sure we could rally up **some** kind of engagement out of that many people. In doing so, it could allow members to become more familiar with each other and become a more cohesive community as a whole. However, this is all based on the assumption we get the engagement in the first place.

I also think for a trial run, we would need to get enough people actually willing to partake in providing a talk in the first place to make it viable, just so we have enough variety in the scheduled talks as mentioned earlier.

I appreciate this is a lot to take on board, I also understand to some it may seem a bit removed from our normal day to day activities as a Discord server but I wanted to at least throw it out there.

I'd really appreciate some feedback. 😄

**Comment by HurricanKai** [comment]
Sounds awesome, I'd 100% tune into interesting stuff and maybe even give a talk if I find something I'm that knowledgeable about.
Regarding additional moderation, I'd only have Associates+ be able to talk (with exceptions for specific people, maybe?) also, besides priority speaker I'd give the one giving a talk the capability to (at least for the duration of the talk) ban people from the voice channel.

One more idea, even though this could be a bit too much and take up too much space, it could be nice to have a way to plan the date with the listeners, which could up listener count too, since it's more likely that people have the time to come at that time

**Comment by RubyNova** [comment]
The problem is that muting banning and priority speaker are server wide, which is why I'm a bit antsy about how we'd make that work well.

But yes I agree only associates should be leading talks for this reason.

**Comment by HurricanKai** [comment]
I guess this would put additional strain on staff, but couldn't a role be handed out for the duration of the talk?

**Comment by RubyNova** [comment]
I mean it's not that much strain, but that could work possibly?

**Comment by HurricanKai** [comment]
I don't see why not, I'd maybe wait a few days for further feedback, and else give it a shot? See what works and what doesn't?

**Comment by RubyNova** [comment]
Sounds good to me!

**Comment by 333fred** [comment]
I'm a fan of the idea, but I don't know if I'd go as far as auto muting everyone other than the speaker to start. Sure, give the speaker some kind of moderation power so they can handle people who talk when they shouldn't, but people asking questions during a presentation is a normal thing and I'd let that happen by default.

**Comment by HurricanKai** [comment]
> if I'd go as far as auto muting everyone other than the speaker
I think that wasn't the intention.
Priority speaker is just that person being louder then others (when pressing a button)
And the Speaker should have the possibility to mute someone to prevent troubles

**Comment by RubyNova** [comment]
> Priority speaker is just that person being louder then others (when pressing a button)

This is the entire point of priority speaker, it lets the main person talking be heard if people are just rambling off topic or have a crappy mic.

**Comment by HurricanKai** [comment]
Thinking about It, it might make sense to require push-to-talk in the channel. Just to minimize background noise. It might be more of an inconvinience for small talks (<10 people) but I wanted to bring it up

**Comment by RubyNova** [comment]
Push to talk would definitely help as it would let the speaker focus a lot easier.

**Comment by 333fred** [comment]
We can say that's required, but I don't know of an actual enforcement strategy. IMO, other than having moderation tools, I don't think we need to go heavy handed here. Either people will be interested in the talk, so they won't be rude, or they need to be moderated, and any requirements we'd put on them would have been ignored anyway.

**Comment by HurricanKai** [comment]
IIRC there's an option in Discord to enforce push to talk

**Comment by RubyNova** [comment]
Yeah you can just turn it on @333fred .

**Comment by CodemanCodes** [comment]
I've never looked deep into how permissions and all work with discord, but if this is an option that people are interested in and it looks like it'll be used going forwards, could Modix eventually be extended for say.. associates or staff to issue a command scheduling the lesson and at that date/time modix automatically give the user that role for the duration of the talk + some additional time for if it runs over.

**Comment by HurricanKai** [comment]
Sounds good, but I'd first see where this goes, before extending Modix

**Comment by HurricanKai** [comment]
So this happened (29/04/2020 21:38)
![image](https://user-images.githubusercontent.com/22711887/80639121-d64c3200-8a61-11ea-9d78-78ee8dc2fcec.png)

**Comment by HurricanKai** [comment]
So what about this?

**Comment by RubyNova** [comment]
Can you clarify what you mean "what about this" @HurricanKai ? Apologies for the late reply, hospital sucks.

**Comment by HurricanKai** [comment]
Sorry, I didn't know you are in hospital, I hope you get well 😅 
I meant to bump this Issue since the last comment was ~2 weeks ago.

**Comment by RubyNova** [comment]
No worries, I'm just unsure what "this" is though.

**Comment by nathan-alden-sr** [comment]
Aside from technical implementation details (leave it to developers to focus on those 😜), I think this is a _great_ idea. There are far too many "learning" resources on .NET and programming in general that just _suck_. The .NET and C# ecosystem are starting to become _the_ ecosystem, and after the various announcements at Build 2020, I am all for helping people learn about the true power of .NET.

That said, anytime scheduling gets involved, it gets tricky. For example, the server has folks spread out all over the world, with specifically high concentrations (from what I'm able to tell) in the United States and the UK. I'm -4 GMT (daylight saving time currently) and it's already an issue working with folks in the UK at work. Trying to coordinate schedules might be pretty difficult.

Live coding sessions _already happen_ on the server--informally, unplanned, unscheduled. I favor working from a position of what we already know and slowly introducing structure and restrictions only if needed. It's tempting to lock everything down and overly formalize things, but the beauty and power of our server and Discord in general is the community spirit. Introducing bureaucracy and rigid formality might endanger that.

I'll likely have additional thoughts on this soon.

**Comment by SuperBrain** [comment]
Regarding permissions and how everything could be organized, here's a quick breakdown
- Create 3 new roles (names are just an example)
  - `SessionSpeaker`
    - Can speak in session-specific voice channel
    - Can write in session-specific text channel
    - Is Priority Speaker
    - Can run session-specific commands influencing both session and participants (commands can be run in session-specific text channel only and stay visible for everyone)
      - Change participant's level (effectively allowing individual participants to talk or muting them)
      - Kick a participant from session (effectively removing their temporarily granted role)
      - Start a session
      - Pause/unpause a session
      - End a session
  - `SessionParticipant1`
    - Can speak
    - Can write in session-specific text channel
  - `SessionParticipant2`
    - Can not speak
    - Can write in session-specific text channel
    - Can run session-specific, participant-related commands in session-specific text channel

Typical flow of a session
1. A member schedules a session using dedicated command
2. Participants RSVP for a session using dedicated command
3. MODiX assigns `SessionSpeaker` 30 minutes (subject to discussion) before session starts effectively allowing Speaker to prepare
4. MODiX assigns `SessionParticipant1` to each subscribed participant 5 minutes (subject to discussion) before session starts
5. Speaker can use `start` command to begin session
6. Speaker can use `pause`/`resume` commands to pause/resume the session respectively, effectively muting everyone (subject to discussion about how to best do this)
7. Speaker can use `mute`/`unmute` command to effectively mute any participant by changing their assigned role
8. Speaker can use `remove` command to effectively kick a participant from session (removes temporarily assigned roles)
9. Participants can can use `talk` command to request talking rights (if currently muted)
10. Speaker can use `end` command to finish the session, effectively removing their and every participant's temporarily assigned roles

Again, this is just a suggested flow and is (as everything else) subject to discussion and further refinement.

I hope this helps.

**Comment by RubyNova** [comment]
To clarify a point for @nathan-alden-sr - this idea isn't intended to replace those informal hangouts or to ban them or something like that, its more for dedicated, preordained workshops that people explicitly want to give. It should also provide means to convey that information publicly within the server itself, so it is transparent and people who might be interested are made aware of it.

Its intended to support those who enjoy giving dedicated sessions, as opposed to "hi im just here working on some program randomly in hangout", its a different thing, if you will. :D

**Comment by nathan-alden-hp** [comment]
@RubyNova I understand that. The spirit isn't what I'm cautioning against; it's just that most of the comments in this thread so far have to do with operational details and restrictions of some kind. I think it's easy to get lost in technical minutia and end up with something that is overly-formalized. The furthest I'd go is constructing a schedule with an agenda and allowing it to be free-form. Add restrictions and formality only if necessary.

**Comment by RubyNova** [comment]
There wouldn't be restrictions - again, all I want is infrastructure to support more dedicated sessions that people may or may not want to run. If something is deemed to be against my intention I'm not gonna include it, so I wouldn't worry about restrictions or whatever because nothing I originally suggested was suggested with the intention of restricting stuff. :D

**Comment by spixy** [comment]
Ok this got a bit stuck so this is what I thought based on SuperBrain comment:

- `!session add {name} {ISO-8601? date} {description?}` (description optional)
  - creates text channel `{name}` with description containing `{date-in-UTC}` and `{description?}` so users can see next sessions and can discuss about them in advance.
  - writes about new session to #join-in or #sessions

Modix can `xx` minutes before the session create voice channel.

User who created session and other speakers (aka `SessionSpeaker`) can inside of text channel do:
- `!session open` - forces to create voice channel now
- `!session +s {user}` - adds speaker
- `!session -s {user}` - removes speaker
- `!session +p {user}` - adds participant
- toggle slowmode through Discord channel settings
- `!session close` - disconnect all and either:
  - removes both text and voice channel?
  - rename text channel to `{name}-{date-in-UTC}` and archive it?

Other users (aka `SessionParticipant2`):
- are automatically muted when joined voice channel
- `!session talk {optional reason?}` - asks for participant role (aka `SessionParticipant1`) so they can talk

btw @SuperBrain what should `start` command do?

**Comment by SuperBrain** [comment]
@spixy basically, the idea is to have commands that effectively start/pause/end the session. When `SessionStartTime` begins, `SessionSpeaker` can issue the `start` command to effectively start it. This can be used to start a timer (for whatever purposes). When `pause` command is issued, session would enter the "paused state" effectively pausing the session timer and muting everyone. `SessionSpeaker` would have to enter `resume` command to continue or `end` command to finally stop the session at the end. All these commands (which are only a suggestion because they would make things a bit complicated to manage) are simply used to control the flow of session, nothing more.

**Comment by HurricanKai** [comment]
@spixy I don't think it's a good idea to have participants ask for speaking permission.
Imo the speaker should be able to configure the push-to-talk requirement (default: on) and remove people from the session.
But I think there should first be even a single session before it makes sense to discuss more fine grained control.

**Comment by spixy** [comment]
So what about this issue?

**Comment by HurricanKai** [comment]
#Join-in has been created, but so far no one used it (I believe) see https://discordapp.com/channels/143867839282020352/712471597918715995/712472647643955263

**Comment by spixy** [comment]
Yeah, maybe we need to motivate people to do sessions... For start with some mentor role?
