### ISSUE TITLE
Open source project requirement clarification

### ISSUE THREAD

**Issue by Perksey** [discord-csharp/meta#14]
> **Share your Project**
> We encourage you to share your .NET project in #projects. Make sure it's publicly available, under an open-source license, and is within in the .NET ecosystem. When posting, make sure to use the following format - and only make a single post per project.
> ```
> Name: 
> Purpose: 
> Main Contributor:
> Source:
> ```

Currently the rules for project posting state that all projects posted must be licensed under an open source license. I fully agree with this, however what constitutes as an open source license is undefined and subjective in nature.

I propose that the rules be adjusted as follows:
```diff
-under an open-source license
+under an open-source license approved by the Open Source Initiative or Open Knowledge Foundation
```

Per a discussion with Aoba in modmail, I found that these are similar to the conditions that the mod team already use when assessing project licenses today, however it has not been formalized as such in the rules or codex. Removing ambiguity from the definition ensures that we are clear on what is meant by an open-source project, as well as ensures all projects meet the [open source definition](https://en.wikipedia.org/wiki/The_Open_Source_Definition) for software, or the [open definition](https://en.wikipedia.org/wiki/The_Open_Definition) for other .NET-related non-software works.

**Comment by Xymanek** [comment]
I will wait for the day when someone will submit a project with WTFPL but it will be denied since it's not OSI-approved

https://en.wikipedia.org/wiki/WTFPL

**Comment by patrickklaeren** [comment]
We can get really uptight about it and moderate it to this extent, but I feel like it's worth having people share projects that don't violate terms of service and teach those people rather than straight up remove them, if that's the goal. We can see about changing the rules to make it explicit, but I don't think that will stop posts happening without licenses from people who are just trying to share their first project.
