### ISSUE TITLE
Reworking structure of authority

### ISSUE THREAD

**Issue by DylanGTech** [discord-csharp/meta#17]
Normally I am not one to participate in anything that could be seen as drama, but I find it important for the sake of inclusion that the server be seen as a place for people to talk about the love of C# as well as software development, and that personal biases or drama be left outside the system of authority. There have been instances in the past where those with power allow such topics to be discussed openly on a plethora of platforms, then recscinding the policy without warning. I would strongly suggest that going forward, politics, religion, and controversial topics be kept away from conversation in our community all the time, including by official events. I spoke with @RubyNova about this earlier. We had some major disagreements about this, so I am appealing to the community overall in hopes of getting other opinions. That's all. Merry Christmas everyone!

**Comment by RubyNova** [comment]
There is nothing to appeal to here. You were banned for incredibly homophobic comments in the C# server. Literally just stop. I am not lifting the ban. Regardless of the event being in or out of the server you still personally fucked up.

Quit it.
