### ISSUE TITLE
Provide a voice chat channel for game streaming

### ISSUE THREAD

**Issue by tannergooding** [discord-csharp/meta#5]
We currently have #hangout-voice under `Collaborate` but it is also frequently used to stream games and other bits; which is a bit odd since we generally want to regulate "offtopic" conversations to the `Offtopic` group.

I would propose we expose a separate voice chat channel specifically for offtopic things, like game streaming, under the `Offtopic` grouping.

**Comment by svengeance** [comment]
I only accept this _provided that_ the first use of this channel is to stream Ruby and I's SC2 showdown

**Comment by RubyNova** [comment]
I am more than happy to make that happen. Come at me.

**Comment by Tylertron1998** [comment]
I completely agree with this. Perhaps a text channel to go along with it, much like #hangout-notes?

**Comment by RubyNova** [comment]
on a serious note; if this does happen the current hangout channels should be given their old names once again, `Code Hangout` and `code-hangout-notes`.

**Comment by Pyrobolser** [comment]
I agree that would be a good idea to have separate channel for game streaming purposes.

**Comment by Inzanit** [comment]
Works for me!

**Comment by 333fred** [comment]
I'm honestly not entirely sure about this. Can you be in multiple hangouts at once? I've seen times before where Ruby or Monica will be streaming some code stuff while someone else is playing a game of some kind, and it's nice for everyone to be able to talk while that's going on.

**Comment by tannergooding** [comment]
That's fair although, sometimes people also want to stream a game or chat about code without the other going on.

Maybe there is some compromise we could have where it's fine to stream in hangout provided you are also willing to help with code questions/etc.

**Comment by svengeance** [comment]
I dig that. Being honest, have we had scenarios where there were people in VC wanting to code & stream at the same time, and the two groups were conflicting?

**Comment by tannergooding** [comment]
It's happened a couple times I've been in there, but I'm not sure how frequent it is overall.

Hence opening the suggesting and hearing input from others 😄

**Comment by UchuuHamster** [comment]
It would be a nice idea but I don't think there's much demand for it :)

Maybe just keep channels to what we absolutely need.

**Comment by 333fred** [comment]
Tanner and I talked about this a bit offline. One suggestion we came up with was having a dedicated help voice chat channel, which would be used for users actually looking to get help on a specific problem, and a channel for general hangout that isn't help-dedicated.

**Comment by tannergooding** [comment]
I think the current proposals are as follows:

❤️ - Keep as is, no changes (streaming games/general chat still allowed)
👀 - Move `#hangout` under `More` as an offtopic channel (coding questions still allowed)
🎉 - Move `#hangout` under `More`, but also introduce a new channel under `Collaborate` specifically for coding questions

I'll keep this open for 48 hours and then will move forward from there based on results.

**Comment by Inzanit** [comment]
I'm personally scared of introducing too many channels, so moving hangouts under more is a good compromise for me, if not leaving it as is.

**Comment by tannergooding** [comment]
Closing this based on the feedback given. Thanks!
