### ISSUE TITLE
Add "Project" and issue labels

### ISSUE THREAD

**Issue by Foxtrek64** [discord-csharp/meta#6]
It'd be really useful to have a kanban board to keep track of suggestions and their current status. Fortunately, GitHub provides one for us, and it can even be automated.

Proposed columns:

* Untriaged - All new issues go here
* Discussion - For issues which are currently receiving feedback
* Under Review - For issues currently being discussed by staff
* Closed - For issues which are closed because the suggested change has been implemented, dismissed, or otherwise closed for any reason.

We may want to split closed into approved/denied/other, but I'm not sure if this is particularly necessary.

**Comment by Inzanit** [comment]
We've got "discussion" and "under-review" at the moment. These things pertain to currently being discussed and those under review by staff or the relevant people who will implement said thing.

I feel overloading the labels too much will cause a lot more admin work than necessary. I personally would like to keep this a simple process. The closing of issues can be handled through the native GitHub issue closing process.

**Comment by Foxtrek64** [comment]
I think those two labels satisfy the suggestion.

"Untriaged" could simply be anything without a label.
"Discussion" is "suggestion"
"Under Review" is "under-review"
And "Closed doesn't really need a label - it's just, as you say, "handled through the native GitHub issue closing process."

In that sense, this only leaves the kanban board, which we can wire up to each of the labels quite easily.

**Comment by 333fred** [comment]
I definitely agree here. We have a bunch of issues open but no real insight into whether staff has discussed them or not. I would also like to suggest an SLA of sorts: nothing too onerous, but a general "Staff will comment within X days".

**Comment by Inzanit** [comment]
> We have a bunch of issues open but no real insight into whether staff has discussed them or not.
This process is still new so you might need to bear with us a little, figuring it out. We have a `under-review` label for the staff that is being discussed. Could be renamed though to make it more obvious it's now being discussed actively by staff instead of just comments on GitHub?

> I would also like to suggest an SLA of sorts
We can definitely provide. I am looking at improving the automation of this repo, i.e. adding a bot to add labels as and when required etc. Will add this to the list.

**Comment by Foxtrek64** [comment]
> 
> 
> 
> This process is still new so you might need to bear with us a little, figuring it out. We have a `under-review` label for the staff that is being discussed. Could be renamed though to make it more obvious it's now being discussed actively by staff instead of just comments on GitHub?

I think the name is probably alright. But I would like to see an organized listing of these somewhere. The search function would be pretty good but the kanban board would be the best solution.

We might want to add a tag for "accepting-feedback" or something, like the pull #2.

**Comment by Inzanit** [comment]
We'll continue to adapt - I am now back and able to update this repository to make sure it's being used. Closing this out for now, feel free to reopen or open up a new issue to get it resolved in a way you find appropriate.
