### ISSUE TITLE
Resources channel

### ISSUE THREAD

**Issue by Adomix** [discord-csharp/meta#7]
A channel with resources from trusted members, presumably associate+ would be pretty nice. Today I (Mango) ran into an occurence where Distilld posted an article a bit ago with a full explanation of TAP and I can't seem to find it. A resource channel would be an easy way to collectively gather resources people find truly helpful. Not even necessarily beginner articles but any resource that somebody feels is beneficial.

**Comment by hizamakura** [comment]
Sounds like it can be easily solved with tags. Having a resource channel has the disadvantage of losing what you're going to look for anyways when it's filled up.
If you're really going to run with the idea, the channel could be read-only with only the useful tags listed in it.

**Comment by Tvde1** [comment]
People would include tags/keywords in their message along with the resource. Discord search can do the rest.

**Comment by hizamakura** [comment]
The problem with that is that they'd have to know *it exists* anyways.
Not only that, the bigger it is the worse it will be to know what those will be.
It would be *kind* of workable with little snippets with embeds, if that will be a thing.

**Comment by AdmiralSnyder** [comment]
i also wish for a curated list of libraries/nuget packages that can be searched by topic/idea/problem-to-solve

**Comment by 333fred** [comment]
That sounds more like a job for a github repo or gist.

**Comment by tannergooding** [comment]
> That sounds more like a job for a github repo or gist.

What about utilizing the github wiki or having a resources folder in this repo?

**Comment by Adomix** [comment]
@tannergooding I think he was replying to Snyder and not my suggestion

**Comment by Adomix** [comment]
@hizamakura We don't need 1500 tags though :thinking:

**Comment by tannergooding** [comment]
I viewed it as to both.

Discord is great for chat; I've not found it so great for collaborative editing or sharing of categorized resources.
Github (having folders) and wikis on the other hand are great for just those purposes.

Having a resources channel in the guild with a link back to the wiki/repo seems like it might be a viable compromise where discussion can be had while still allowing easy finding, searching, and categorization of those resources.

**Comment by 333fred** [comment]
I mean, it was more of a direct reply to Adam, but I do think the idea applies in general. Keeping an organized list is not a job for discord.

**Comment by Pyrobolser** [comment]
It doesn't sound like it would be easy to do that in a Discord channel.
You would have to rely on the search every time you want to find something, it can get really messy.

One example of resources page that I find useful for example is https://free-for.dev/ with the [underlying GitHub repository](https://github.com/ripienaar/free-for-dev). It is categorized and easy to find something or just browse. I agree that using the wiki instead of a channel for this purpose sounds better.

**Comment by Inzanit** [comment]
I agree with the general consensus here that this is difficult to curate a channel of resources - over time they will be lost and the same issue of people not knowing what is available in a channel exists. Would much rather favour a repository/website here.

**Comment by Inzanit** [comment]
Closing this out for now, as there hasn't been too much more conversation since. Happy to reevaluate if we find something that would help us retain a "good" list within a Discord channel.
