### ISSUE TITLE
Add DM Rule/Note

### ISSUE THREAD

**Issue by Foxtrek64** [discord-csharp/meta#9]
I'm not sure if this needs to be an actual *rule*, but I feel it should be stated somewhere visible, especially since this is a common question.

> We do not offer support through direct messages. Questions should be asked in public channels to ensure that others may contribute and benefit from the question being asked.

Optionally, we may add the following disclaimer:
> Attempts to ask for support in direct messages to bypass server rules or the Discord Terms of Service may be met with punitive actions.

Couple of notes:

1. I thought of doing this as a tag, but I feel that his may come off as dismissive or rude. I get that a lot of people don't read the rules first thing (or at all), but being able to point to something "official" may help in understanding.
1. I know we don't enforce/regulate/moderate direct messages between users, though this is why it is left vaguely to "punitive actions." If, say, a user DMs you to ask for help with a cracking or cheat tool for their favorite video game, you might report them to Discord, block them, or even report it to a staff member so a note can be made not to help the user with that specific topic. I think all of these things could, with enough flexing, be construed to be "punitive actions."
1. Wording is not set in stone. If you have different ideas for wording, this should also be discussed.

**Comment by tannergooding** [comment]
> We do not offer support through direct messages. Questions should be asked in public channels to ensure that others may contribute and benefit from the question being asked

I, personally, would prefer wording more along the lines of "We strongly encourage questions to be asked in public channels to ensure that others may contribute and benefit from the question being asked."

Any individual user is free to offer support/etc through DMs and that may even be beneficial in some scenarios to prevent everyone from giving conflicting answers, etc.
Some drawbacks are that you can't easily hand off that help to someone else if you need to leave and other people can't benefit from the answers given.
But if both you and the user involved are fine with that, then that is on you and there isn't anything we can do to prevent it.

We currently have the latter disclaimer you mentioned as part of the `#rules`:
> 6) Using the member list of this guild to target users' private messages in order to break rules is forbidden.

But it is being removed in #2 and might be where that feedback should go.

**Comment by Foxtrek64** [comment]
@Inzanit Is #2 still open for input? Comment period ended 5 days ago but the issue is still open.

**Comment by Inzanit** [comment]
Can we add this to the PR, #2 - I will close this issue as it belongs there. Apologies that I didn't update the PR to reflect new close date.
